server:
  port: 8001

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.yewenxue.springcloud.entities

spring:
  application:
    name: cloud-payment-service
  datasource:
    type:  com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name:  org.gjt.mm.mysql.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root